[build]
  functions = "functions"  # This specifies where the serverless functions are located
  publish = "static"  # If you have any static files, specify here

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
