[build.environment]
  RUST_VERSION = "1.56.0"  # Ensure you're using a compatible version of Rust
[build]
  command = "sudo apt-get install -y build-essential python3-dev && bash install_rust.sh && pip install -r requirements.txt && python manage.py collectstatic"

  publish = "/"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-python"
