[build]
  command = "npm run build"
  publish = "dist"

# Handling classic.html and general SPA routing
[[redirects]]
  from = "/classic"
  to = "/classic.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
